// Indian states & union territories — code as used by Bajaj/RTO + full name
export const INDIAN_STATES = [
  { value: 'AN', label: 'Andaman & Nicobar Islands' },
  { value: 'AP', label: 'Andhra Pradesh' },
  { value: 'AR', label: 'Arunachal Pradesh' },
  { value: 'AS', label: 'Assam' },
  { value: 'BR', label: 'Bihar' },
  { value: 'CH', label: 'Chandigarh' },
  { value: 'CG', label: 'Chhattisgarh' },
  { value: 'DD', label: 'Dadra & Nagar Haveli and Daman & Diu' },
  { value: 'DL', label: 'Delhi' },
  { value: 'GA', label: 'Goa' },
  { value: 'GJ', label: 'Gujarat' },
  { value: 'HR', label: 'Haryana' },
  { value: 'HP', label: 'Himachal Pradesh' },
  { value: 'JK', label: 'Jammu & Kashmir' },
  { value: 'JH', label: 'Jharkhand' },
  { value: 'KA', label: 'Karnataka' },
  { value: 'KL', label: 'Kerala' },
  { value: 'LA', label: 'Ladakh' },
  { value: 'LD', label: 'Lakshadweep' },
  { value: 'MP', label: 'Madhya Pradesh' },
  { value: 'MH', label: 'Maharashtra' },
  { value: 'MN', label: 'Manipur' },
  { value: 'ML', label: 'Meghalaya' },
  { value: 'MZ', label: 'Mizoram' },
  { value: 'NL', label: 'Nagaland' },
  { value: 'OD', label: 'Odisha' },
  { value: 'PY', label: 'Puducherry' },
  { value: 'PB', label: 'Punjab' },
  { value: 'RJ', label: 'Rajasthan' },
  { value: 'SK', label: 'Sikkim' },
  { value: 'TN', label: 'Tamil Nadu' },
  { value: 'TS', label: 'Telangana' },
  { value: 'TR', label: 'Tripura' },
  { value: 'UK', label: 'Uttarakhand' },
  { value: 'UP', label: 'Uttar Pradesh' },
  { value: 'WB', label: 'West Bengal' },
]

// Common automobile colours (uppercase, matching RTO records)
export const VEHICLE_COLOURS = [
  { value: 'WHITE', label: 'White' },
  { value: 'BLACK', label: 'Black' },
  { value: 'SILVER', label: 'Silver' },
  { value: 'S. SILVER', label: 'Silky Silver' },
  { value: 'GREY', label: 'Grey' },
  { value: 'RED', label: 'Red' },
  { value: 'BLUE', label: 'Blue' },
  { value: 'PEARL WHITE', label: 'Pearl White' },
  { value: 'MIDNIGHT BLACK', label: 'Midnight Black' },
  { value: 'NEXA BLUE', label: 'Nexa Blue' },
  { value: 'MAGMA GREY', label: 'Magma Grey' },
  { value: 'ARCTIC WHITE', label: 'Arctic White' },
  { value: 'SPLENDID SILVER', label: 'Splendid Silver' },
  { value: 'PREMIUM SILVER', label: 'Premium Silver' },
  { value: 'BROWN', label: 'Brown' },
  { value: 'BEIGE', label: 'Beige' },
  { value: 'MAROON', label: 'Maroon' },
  { value: 'GREEN', label: 'Green' },
  { value: 'ORANGE', label: 'Orange' },
  { value: 'YELLOW', label: 'Yellow' },
  { value: 'GOLDEN', label: 'Golden' },
  { value: 'WINE RED', label: 'Wine Red' },
  { value: 'BURGUNDY', label: 'Burgundy' },
  { value: 'TITANIUM GREY', label: 'Titanium Grey' },
  { value: 'CELESTIAL BLUE', label: 'Celestial Blue' },
  { value: 'ROYAL BLUE', label: 'Royal Blue' },
  { value: 'CERULEAN BLUE', label: 'Cerulean Blue' },
  { value: 'PEARL METALLIC', label: 'Pearl Metallic' },
  { value: 'FIERY RED', label: 'Fiery Red' },
  { value: 'CAFE WHITE', label: 'Cafe White' },
  { value: 'GRANITE GREY', label: 'Granite Grey' },
  { value: 'GLISTENING GREY', label: 'Glistening Grey' },
  { value: 'CARBON STEEL', label: 'Carbon Steel' },
  { value: 'SUPERIOR WHITE', label: 'Superior White' },
  { value: 'PRIME AUBURN RED', label: 'Prime Auburn Red' },
  { value: 'SIZZLING RED', label: 'Sizzling Red' },
  { value: 'TORQUE BLUE', label: 'Torque Blue' },
  { value: 'AUTUMN ORANGE', label: 'Autumn Orange' },
  { value: 'LUSTER BLUE', label: 'Luster Blue' },
  { value: 'BRAVE KHAKI', label: 'Brave Khaki' },
  { value: 'CREAM', label: 'Cream' },
  { value: 'TAN', label: 'Tan' },
  { value: 'PINK', label: 'Pink' },
  { value: 'PURPLE', label: 'Purple' },
  { value: 'NAVY BLUE', label: 'Navy Blue' },
]

// Fuel types
export const FUEL_TYPES = [
  { value: 'PETROL', label: 'Petrol' },
  { value: 'DIESEL', label: 'Diesel' },
  { value: 'CNG', label: 'CNG' },
  { value: 'LPG', label: 'LPG' },
  { value: 'ELECTRIC', label: 'Electric' },
  { value: 'HYBRID', label: 'Hybrid' },
  { value: 'PETROL+CNG', label: 'Petrol + CNG' },
  { value: 'PETROL+LPG', label: 'Petrol + LPG' },
]

// Vehicle types
export const VEHICLE_TYPES = [
  { value: 'Motor Car', label: 'Motor Car' },
  { value: 'Motor Cycle', label: 'Motor Cycle' },
  { value: 'Three Wheeler', label: 'Three Wheeler (Auto)' },
  { value: 'Truck', label: 'Truck' },
  { value: 'Bus', label: 'Bus' },
  { value: 'Mini Bus', label: 'Mini Bus' },
  { value: 'Tractor', label: 'Tractor' },
  { value: 'Trailer', label: 'Trailer' },
  { value: 'Light Motor Vehicle', label: 'Light Motor Vehicle (LMV)' },
  { value: 'Heavy Motor Vehicle', label: 'Heavy Motor Vehicle (HMV)' },
  { value: 'Multi Utility Vehicle', label: 'Multi Utility Vehicle (MUV)' },
  { value: 'Sport Utility Vehicle', label: 'Sport Utility Vehicle (SUV)' },
  { value: 'Pick Up', label: 'Pick Up' },
  { value: 'Van', label: 'Van' },
  { value: 'Jeep', label: 'Jeep' },
  { value: 'Construction Equipment', label: 'Construction Equipment' },
]
